version: '3.3'
services:
  app:
    image: app
    build: .
    container_name: rest_backend
    ports:
      - "8080:8080"
      - "5005:5003"
    restart: always
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  # Database Service (postgres)
  postgres:
    image: "postgres:10.7"
    container_name: container-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_USER=pg1user
      - POSTGRES_DB=security